---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-lyceum
  namespace: lyceum
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-33d072d3.efs.us-east-1.amazonaws.com
    path: "/lyceum"
