---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-lyceum-claim
  namespace: lyceum
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
