apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hygia
  name: hygia
  selfLink: /api/v1/namespaces/hygia/services/hygia
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30414
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30766
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: hygia
    tier: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
