---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: blog-hygia-prd
  namespace: blog-hygia
  labels:
    app: blog-hygia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-hygia
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-hygia
        tier: frontend
    spec:
      containers:
      - image: 784862261167.dkr.ecr.us-east-1.amazonaws.com/wp_blog_hygia:blog-hygia-prd-03
        name: blog-hygia-prd-03
        env:
        - name: WORDPRESS_DB_HOST
          value: wptechneprd.cgexaccvir8f.us-east-1.rds.amazonaws.com
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: blog-hygia
        volumeMounts:
        - name: efs-blog-hygia
          mountPath: /usr/share/nginx/blog_hygia
      volumes:
      - name: efs-blog-hygia
        persistentVolumeClaim:
          claimName: efs-blog-hygia-claim
