---
apiVersion: v1
kind: Service
metadata:
  name: blog-hygia
  namespace: blog-hygia
  labels:
    app: blog-hygia
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  selector:
    app: blog-hygia
    tier: frontend
  type: LoadBalancer
