---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: intra-techne-prd
  namespace: intra-techne
  labels:
    app: intra-techne
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intra-techne
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: intra-techne
        tier: frontend
    spec:
      containers:
      - image: 784862261167.dkr.ecr.us-east-1.amazonaws.com/wp_intratechne:intra-techne-prd
        name: intra-techne-prd
        env:
        - name: WORDPRESS_DB_HOST
          value: wptechneprd.cgexaccvir8f.us-east-1.rds.amazonaws.com
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: intra-techne
        volumeMounts:
        - name: efs-intra-techne
          mountPath: /usr/share/nginx/intratechne
      volumes:
      - name: efs-intra-techne
        persistentVolumeClaim:
          claimName: efs-intra-techne-claim
