---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-intra-techne-claim
  namespace: intra-techne
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
