---
apiVersion: v1
kind: Service
metadata:
  name: intra-techne
  namespace: intra-techne
  labels:
    app: intra-techne
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: intra-techne
    tier: frontend
  type: LoadBalancer
