---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ergonrh-hmg
  namespace: ergonrh-hmg
  labels:
    app: ergonrh-hmg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ergonrh-hmg
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ergonrh-hmg
        tier: frontend
    spec:
      containers:
      - image: 784862261167.dkr.ecr.us-east-1.amazonaws.com/wp_ergonrh:ergonrh-hmg
        name: ergonrh-hmg
        env:
        - name: WORDPRESS_DB_HOST
          value: wptechneprd.cgexaccvir8f.us-east-1.rds.amazonaws.com
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: ergonrh-hmg
        volumeMounts:
        - name: efs-ergonrh-hmg
          mountPath: /usr/share/nginx/ergonrh
      volumes:
      - name: efs-ergonrh-hmg
        persistentVolumeClaim:
          claimName: efs-ergonrh-hmg-claim
