---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-ergonrh-hmg-claim
  namespace: ergonrh-hmg
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
