---
apiVersion: v1
kind: Service
metadata:
  name: esocial-techne
  namespace: esocial-techne
  labels:
    app: esocial-techne
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: esocial-techne
    tier: frontend
  type: LoadBalancer
