---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-lyceum-blog-claim
  namespace: lyceum-blog
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
