---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: blog-ergonrh-prd
  namespace: blog-ergonrh
  labels:
    app: blog-ergonrh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-ergonrh
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-ergonrh
        tier: frontend
    spec:
      containers:
      - image: 784862261167.dkr.ecr.us-east-1.amazonaws.com/wp_blog_ergonrh:latest
        name: blog-ergonrh-prd
        env:
        - name: WORDPRESS_DB_HOST
          value: wptechneprd.cgexaccvir8f.us-east-1.rds.amazonaws.com
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: blog-ergonrh
        volumeMounts:
        - name: efs-blog-ergonrh
          mountPath: /usr/share/nginx/blog_ergonrh
      volumes:
      - name: efs-blog-ergonrh
        persistentVolumeClaim:
          claimName: efs-blog-ergonrh-claim
