---
apiVersion: v1
kind: Service
metadata:
  name: blog-ergonrh
  namespace: blog-ergonrh
  labels:
    app: blog-ergonrh
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  selector:
    app: blog-ergonrh
    tier: frontend
  type: LoadBalancer
