---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-hygia
  namespace: hygia
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-33d072d3.efs.us-east-1.amazonaws.com
    path: "/hygia"
