---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-hygia-claim
  namespace: hygia
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
