---
apiVersion: v1
kind: Service
metadata:
  name: hygia
  namespace: hygia
  labels:
    app: hygia
spec:
  ports:
    - name: http
      protocol: tcp
      port: 80
    - name: https
      protocol: tcp
      port: 443
  selector:
    app: hygia
    tier: frontend
  type: LoadBalancer
